<a href="https://colab.research.google.com/github/AndresRico/CursoPythonAIiF/blob/main/Tema5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Índices en listas

In [5]:
A = [89, 2, 3, 4, 5]
print(A)

print(A[0])

A[0] = 1

print(A)

A[4] = 109

print(A)


[89, 2, 3, 4, 5]
89
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 109]


#Anadir elementos a listas

In [7]:
B = [1,2,3]
B

B.append(4)

B

[1, 2, 3, 4]

In [11]:
C=[]

C

C.append([1,2,3])
C
C.append([4,5,6])
C
C.append([7,8,9])
C

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
#import numpy as np
#C = np.array(C)
#C


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#Operaciones a listas




In [16]:
print(C[0])
print(C[1])

print(C[1][0])

print(C[2][2])



[1 2 3]
[4 5 6]
4
9


In [18]:
D = [1,2,3,4,5,6,7,8,9,10]
D

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [19]:
Suma = sum(D)
Suma

55

In [20]:
Longitud = len(D)
Longitud

10

In [21]:
Promedio = sum(D)/len(D)
Promedio

5.5

In [22]:
import statistics as st
Promedio2 = st.mean(D)
Promedio2

5.5

#Listas con Strings

In [24]:
Cadenas = ["abc","def","ghi","jkl"]
print (Cadenas)

print (Cadenas[3][2])

['abc', 'def', 'ghi', 'jkl']
l


In [25]:
Longitud = len(Cadenas)
Longitud

4

In [33]:
print(Cadenas[0:2])

print (Cadenas[2][0:2])

['abc', 'def']
gh


#Diccionarios

In [36]:
Datos_Alumno = {
    "Nombre":"Octavio",
    "Apellido":"Paz",
    "Matrícula":"123456",
    "Horario":"Matutino",
    "Beca":"Si"}

In [41]:
print(Datos_Alumno["Matrícula"])
print(Datos_Alumno["Apellido"])
print(Datos_Alumno["Beca"])

123456
Paz
Si


In [44]:
Datos_Alumno.update({"Materias":["Física","Química","Programación"]})
Datos_Alumno

{'Apellido': 'Paz',
 'Beca': 'Si',
 'Horario': 'Matutino',
 'Materias': ['Física', 'Química', 'Programación'],
 'Matrícula': '123456',
 'Nombre': 'Octavio'}

In [46]:
print(Datos_Alumno["Materias"])
print(Datos_Alumno["Materias"][0:2])

['Física', 'Química', 'Programación']
['Física', 'Química']


#Diccionarios anidados

In [53]:
Pacientes = [
             {
              "Nombre":"Juan",
              "Seguro":"Si",
              "ID_seguro":"987654321",
              "Covid":"Si",
              "G_sanguineo":"AB+"
             },
             {
              "Nombre":"María",
              "Seguro":"Si",
              "ID_seguro":"123456789",
              "Covid":"No",
              "G_sanguineo":"A+"
             },
             {
              "Nombre":"Ernesto",
              "Seguro":"No",
              "ID_seguro":"N/A",
              "Covid":"No",
              "G_sanguineo":"B+"
             }
]

Pacientes[0]

print(Pacientes[1]["Nombre"])
print(Pacientes[1]["Seguro"])
print(Pacientes[1]["ID_seguro"])

María
Si
123456789


In [57]:
print(Pacientes[2]["Seguro"])
print(Pacientes[2]["Covid"])
print(Pacientes[2]["G_sanguineo"])

No
No
B+


In [58]:
print(Pacientes[0]["G_sanguineo"][0:2])

AB


#TAREA


*   Anidar diccionarios (mínimo 2)
*   El programa solicite que teclees el valor de las variables
*   Luego estas se agreguen al diccionario con **UPDATE**



In [81]:
#Definición del diccionario

biblio =[{
    "título":"El principito",
    "autor":"Antoine de Saint-Exupéry",
    "año":1943
    },
    {
    "título":"El ingenioso Hidalgo Don Quijote de la Mancha",
    "autor":"Miguel de Cervantes Saavedra",
    "año":1605
    }
    ]

#Se van a agregar un par de campos a cada registro del diccionario anidado

biblio[0].update({"género":"Literatura infantil"})
biblio[1].update({"género":"Novela clásica"})
biblio[0].update({"calificación":4.8})
biblio[1].update({"calificación":3.8})

#Se van a introducir nuevos registros al diccionario, pero será el usuario el que los agregue

título = input("Da el título del libro ")
autor = input("Da el nombre del autor ")
año = int(input("Introduce el año de publicación "))
género = input("Introduce el género pertenece el libro ")
calificación = float(input("Introduce la calificación que le das a este libro "))

biblio.append({
    "título":título,
    "autor":autor,
    "año":año,
    "género":género,
    "calificación":calificación
})

print(biblio)
#print(type(biblio))



#Actualización del diccionario para agregar un par de campos más
 #   "género": "Literatura infantil",
  #  "isbn":"9780156013925"



Da el título del libro Ready player one
Da el nombre del autor Ernest Cline
Introduce el año de publicación 2011
Introduce el género pertenece el libro Ciencia ficción
Introduce la calificación que le das a este libro 4.3
[{'título': 'El principito', 'autor': 'Antoine de Saint-Exupéry', 'año': 1943, 'género': 'Literatura infantil', 'calificación': 4.8}, {'título': 'El ingenioso Hidalgo Don Quijote de la Mancha', 'autor': 'Miguel de Cervantes Saavedra', 'año': 1605, 'género': 'Novela clásica', 'calificación': 3.8}, {'título': 'Ready player one', 'autor': 'Ernest Cline', 'año': 2011, 'género': 'Ciencia ficción', 'calificación': 4.3}]
